### ISSUE TITLE
api:GetPageTextStructured  The extracted information has repeat areas

### ISSUE THREAD

**Issue by FortuneW** [klippa-app/go-pdfium#145]
Hi,

I tested and found that the GetPageTextStructured function extracts results with repeat areas

For example, the following ：

[0001.json](https://github.com/klippa-app/go-pdfium/files/14495353/0001.json)
[0001.pdf](https://github.com/klippa-app/go-pdfium/files/14495354/0001.pdf)

Here is a specific error:
```json
  {
   "left": 36.88567352294922,
   "top": 215.13877868652344,
   "right": 87.23951721191406,
   "bottom": 207.6760711669922,
   "text": "hibernators ("
  },
  {
   "left": 87.57408905029297,
   "top": 214.72274780273438,
   "right": 92.2285385131836,
   "bottom": 208.967529296875,
   "text": "5)"
  },
  {
   "left": 92.16873168945312,
   "top": 215.13877868652344,
   "right": 96.52155303955078,
   "bottom": 207.6760711669922,
   "text": "5)."
  },
```

The original text is：
![wrong-pos](https://github.com/klippa-app/go-pdfium/assets/20201626/7520f2c9-5883-4ac3-be85-60690427d865)

**Comment by jerbob92** [comment]
@FortuneW I think you have to go to pdfium to get this fixed, this way this code works is:

- Use `FPDFText_CountRects` to get the amount of rects in the page
- Use `FPDFText_GetRect` for each rect to get the coordinates of that rect
- Use `FPDFText_GetBoundedText` to get the text within that rect 

I suspect that pdfium has split up the rects for that sentence because of a mix in the font styles, it looks like the `5` is in italic. Because the `5` is in italic and titled to the right, the bounding box overlaps with other text. If you look closely, you see that 5 falls a bit over `(` and `)`. The actual rects should be: "hibernators (", "5" and ").". 

In my opinion this could be fixed in 3 ways:
 - pdfium should not split the rects based on the style and this should just be one rect with the text `hibernators (5).`, or:
 - pdfium should return a proper rect (so not a straight square but also a bit titled), or:
 - pdfium should provide a method to directly get the text of a rect (so without the coordinate step in between)

**Comment by FortuneW** [comment]
@jerbob92 
Got it,Thank you for your analysis and suggestions. I will try some methods to fix such problems

**Comment by FortuneW** [comment]
Nice to synchronize with you,

I have rewritten a function similar to GetPageTextStructured using the following function:

- FPDFPage_CountObjects
- FPDFPage_GetObject
- FPDFPageObj_GetType
- FPDFFormObj_CountObjects
- FPDFFormObj_GetObject
- FPDFTextObj_GetText
- FPDFPageObj_GetBounds

So far, it works well.

**Comment by FortuneW** [comment]
Nice to synchronize with you,

I have rewritten a function similar to GetPageTextStructured using the following function:

- FPDFPage_CountObjects
- FPDFPage_GetObject
- FPDFPageObj_GetType
- FPDFFormObj_CountObjects
- FPDFFormObj_GetObject
- FPDFTextObj_GetText
- FPDFPageObj_GetBounds

So far, it works well.

**Comment by FortuneW** [comment]
Nice to synchronize with you,

I have rewritten a function similar to GetPageTextStructured using the following function:

- FPDFPage_CountObjects
- FPDFPage_GetObject
- FPDFPageObj_GetType
- FPDFFormObj_CountObjects
- FPDFFormObj_GetObject
- FPDFTextObj_GetText
- FPDFPageObj_GetBounds

So far, it works well.

**Comment by jerbob92** [comment]
@FortuneW that's a nice solution!
