### ISSUE TITLE
Bitmap generation with alternative fonts

### ISSUE THREAD

**Issue by nonchan7720** [klippa-app/go-pdfium#68]
Nice to meet you and thank you for making a good library.

How should we do if we want to shy an alternative font when the font in the PDF is not found?
We are experiencing an event where characters are lost when generating a Bitmap from a PDF because the font is not found.

**Comment by jerbob92** [comment]
pdfium looks in a few different folders for fonts (depending on your OS):
https://pdfium.googlesource.com/pdfium/+/refs/heads/main/core/fxge/linux/fx_linux_impl.cpp#169
https://pdfium.googlesource.com/pdfium/+/refs/heads/main/core/fxge/apple/fx_apple_platform.cpp#148

You can also give extra paths in go-pdfium to look for fonts when initializing the library:
https://github.com/klippa-app/go-pdfium/blob/main/pdfium.go#L10

Generally it should be enough to have a default set of fonts, but I did notice it might help to install `msttcorefonts` to get some Windows fonts because some PDF renderers do not embed fonts and expect the Windows fonts to always be available.

**Comment by nonchan7720** [comment]
@jerbob92 
Thank you for your reply.
I am using Wasm, is it the same?

**Comment by jerbob92** [comment]
WASM uses a linux-like build, so the font folders the same as the Linux build:

- /usr/share/fonts
- /usr/share/X11/fonts/Type1
- /usr/share/X11/fonts/TTF
- /usr/local/share/fonts

If you provide your own `FSConfig` in the initialization, make sure that the font folder is mounted into the available folders for pdfium.

**Comment by nonchan7720** [comment]
Thank you very much!

How should alternative fonts be specified? 🙇‍♂️

**Comment by jerbob92** [comment]
pdfium doesn't expose an easy method to control that, the only way to do it is by implementing `fpdf_sysfontinfo.h`, which is one of the few things that this library did not implement (yet), due to the complicated nature of those methods. 

I might look into adding support for this later, but generally PDF's should not use fonts that aren't widely installed on machines as it will cause render issues, that's why PDF's embed fonts if they are not installed by default on machines. Afaik pdfium tries to fall back to Arial when it can't find the requested font.

Could you try to check which font the PDF is trying to load?

**Comment by nonchan7720** [comment]
I have to process PDFs that are given to me by another user, and in some cases the PDFs use commercial fonts, and I would like to use an alternative font.

**Comment by nonchan7720** [comment]
Yes, it is.

**Comment by jerbob92** [comment]
That is not possible right now. 
It might be possible when `fpdf_sysfontinfo.h` is implemented, but I do not know for sure, it might be that pdfium will always load the embedded font when it's available. 

I would have to look into it, will let you know!

**Comment by nonchan7720** [comment]
I look forward to the day when we can get good information!

**Comment by jerbob92** [comment]
I did some tests and got a nice starting point (in the CGO implementation) with the implementation of `fpdf_sysfontinfo.h`. However, I have sad news for you. Pdfium only calls the custom font mapper when it renders a font that is not embedded inside the PDF. 

I will probably complete the implementation (for WASM too) while I'm at it, but it won't be useful for you I'm afraid. 
You could try to ask [here](https://groups.google.com/g/pdfium) for pdfium to add a feature to also use the custom font mapper for embedded fonts.

**Comment by jerbob92** [comment]
I will close this issue for now.
